# Generated by Django 6.0 on 2026-01-27 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('titulo', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('versao', models.CharField(choices=[('original', 'Original'), ('modernizado', 'Modernizado'), ('imagem', 'Imagem')], max_length=20)),
                ('conteudo', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='poema/')),
                ('canto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas', to='homepage.canto')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('canto', 'numero', 'versao')},
            },
        ),
    ]
