# Generated by Django 6.0 on 2026-01-27 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('imagem', models.ImageField(upload_to='poema/')),
                ('canto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas', to='homepage.canto')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('canto', 'numero')},
            },
        ),
        migrations.DeleteModel(
            name='Pagina',
        ),
    ]
