# Generated by Django 6.0 on 2026-02-07 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_paginaimagem_delete_pagina'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paginaimagem',
            options={'ordering': ['numero'], 'verbose_name': 'Página de imagem', 'verbose_name_plural': 'Páginas de imagens'},
        ),
    ]
