# Generated by Django 6.0 on 2026-02-07 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_paginaimagem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaTexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('versao', models.CharField(choices=[('original', 'Original'), ('modernizado', 'Modernizado')], max_length=20)),
                ('tei_xml', models.TextField(help_text='Cole aqui o TEI-XML')),
                ('canto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textos', to='homepage.canto')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('canto', 'numero', 'versao')},
            },
        ),
    ]
